import Doc from "@/types/doc";

const DOCUMENTS: Doc[] = [
  {
    _id: "d1",
    title: "Service Agreement 2026.pdf",
    fileType: "pdf",
    fileSize: 248000,
    fileUrl: "https://example.com/files/service-agreement-2026.pdf",
    status: "completed",
    isShared: true,
    folder: "f1",
    rawText: "This Service Agreement is entered into between...",
    user: "u1",
    createdAt: "2026-02-01",
  },
  {
    _id: "d2",
    title: "NLP Research Overview.docx",
    fileType: "docx",
    fileSize: 512000,
    fileUrl: "https://example.com/files/nlp-research-overview.docx",
    status: "completed",
    isShared: false,
    folder: "f2",
    rawText: "This paper explores transformer-based architectures in NLP...",
    user: "u1",
    createdAt: "2026-02-03",
  },
  {
    _id: "d3",
    title: "Q1 Strategy Meeting.txt",
    fileType: "txt",
    fileSize: 32000,
    fileUrl: "https://example.com/files/q1-strategy-meeting.txt",
    status: "completed",
    isShared: false,
    folder: "f3",
    rawText:
      "Meeting notes:\n- Increase marketing budget\n- Launch beta version",
    user: "u2",
    createdAt: "2026-02-05",
  },
  {
    _id: "d4",
    title: "Employment Contract Draft.pdf",
    fileType: "pdf",
    fileSize: 189000,
    fileUrl: "https://example.com/files/employment-contract-draft.pdf",
    status: "processing",
    isShared: true,
    folder: "f1",
    rawText: "",
    user: "u1",
    createdAt: "2026-02-10",
  },
  {
    _id: "d5",
    title: "AI Ethics Paper.pdf",
    fileType: "pdf",
    fileSize: 876000,
    fileUrl: "https://example.com/files/ai-ethics-paper.pdf",
    status: "completed",
    isShared: false,
    folder: "f2",
    rawText:
      "Artificial Intelligence ethics involves fairness, transparency...",
    user: "u2",
    createdAt: "2026-02-11",
  },
  {
    _id: "d6",
    title: "Product Roadmap 2026.docx",
    fileType: "docx",
    fileSize: 340000,
    fileUrl: "https://example.com/files/product-roadmap-2026.docx",
    status: "failed",
    isShared: true,
    rawText: "",
    user: "u1",
    createdAt: "2026-02-12",
  },
  {
    _id: "d7",
    title: "Vendor Agreement.pdf",
    fileType: "pdf",
    fileSize: 155000,
    fileUrl: "https://example.com/files/vendor-agreement.pdf",
    status: "uploaded",
    isShared: false,
    folder: "f1",
    rawText: "",
    user: "u3",
    createdAt: "2026-02-14",
  },
  {
    _id: "d8",
    title: "Transformer Architecture.pdf",
    fileType: "pdf",
    fileSize: 1240000,
    fileUrl: "https://example.com/files/transformer-architecture.pdf",
    status: "completed",
    isShared: true,
    folder: "f2",
    rawText:
      "The transformer model relies entirely on self-attention mechanisms...",
    user: "u1",
    createdAt: "2026-02-14",
  },
];

export default DOCUMENTS;
