const isZenithDocsQuestion = (question: string): boolean => {
  const keywords = [
    // Original keywords
    "zenithdocs",
    "zenith docs",
    "zenithsus",
    "features",
    "how to use",
    "this app",
    "this platform",
    "this tool",
    "what can you do",
    "what is this",
    "how does this work",
    "document types",
    "file types",
    "max size",
    "maximum size",
    "summary types",
    "upload",
    "supported formats",
    "supported file formats",
    "created by",
    "developed by",
    "document support",

    // About the Platform
    "what is zenithdocs",
    "who created zenithdocs",
    "who developed zenithdocs",
    "what is zenithsus",
    "what can you do on this platform",
    "how does this app work",
    "what is this tool used for",

    // Features
    "what are the features",
    "what features does this platform",
    "explain the features",
    "features available here",
    "features of zenithdocs",

    // Document Types & Limits
    "what file types are supported",
    "what document types can i upload",
    "what are the supported file formats",
    "what is the maximum size",
    "what is the max size",
    "max size allowed",
    "maximum size for",
    "allowed for documents",

    // Summaries
    "what summary types are available",
    "what kind of summaries",
    "summaries can zenithdocs generate",

    // Usage
    "how do i upload",
    "how to upload",
    "what can you do with uploaded files",

    // User Account & Plan
    "my plan",
    "my account",
    "my subscription",
    "what plan am i on",
    "am i on free",
    "am i on premium",
    "upgrade plan",
    "current plan",
    "my tier",
    "what tier am i on",

    // Usage & Limits
    "my usage",
    "my usage summary",
    "explain my usage",
    "show my usage",
    "my limit",
    "my limits",
    "what are my limits",
    "what is my limit",
    "messages per day",
    "how many messages",
    "how many messages can i send",
    "how many documents",
    "how many documents can i upload",
    "document limit",
    "storage limit",
    "how much storage",
    "how much storage do i have",
    "storage left",
    "remaining storage",
    "how much space",
    "storage used",
    "storage available",

    // Dashboard
    "my dashboard",
    "my overview",
    "my stats",
    "my statistics",
    "my activity",
    "explain my dashboard",
    "show my dashboard",
    "dashboard overview",
    "how many files",
    "how many documents do i have",
    "total documents",
    "total files",
    "my documents",
    "my files",

    // User Info / Profile
    "my email",
    "my profile",
    "who am i",
    "my account info",
    "my account details",
    "my information",

    // Onboarding / Help
    "walkthrough",
    "walk me through",
    "walk through",
    "get started",
    "getting started",
    "how do i start",
    "where do i start",
    "guide me",
    "guide",
    "tutorial",
    "onboarding",
    "help me use",
    "show me how",
    "how to get started",

    // Casual/Conversational
    "what do i do",
    "what should i do",
    "what now",
    "where to begin",
    "where do i begin",
    "how to begin",
    "i'm new",
    "im new",
    "new here",
    "just started",
    "first time",
    "don't know how",
    "dont know how",
    "confused",
    "lost",
    "help me",
    "need help",
    "need guidance",
    "can you help",
    "assist me",
    "teach me",
    "explain to me",
    "tell me how",
    "tell me about",
    "tell me more",
    "how do i use",
    "how can i use",
    "how to navigate",
    "navigate",
    "navigation",

    // Platform overview
    "overview",
    "what's here",
    "whats here",
    "what's in this",
    "what can i do here",
    "what can i do",
    "what do you offer",
    "what does this offer",
    "what's available",
    "whats available",
    "capabilities",
    "what are your capabilities",
    "how does this help",
    "what's the point",
    "whats the point",
    "what's the purpose",
    "whats the purpose",
    "how is this useful",

    // Greetings
    "hi",
    "hello",
    "hey",
    "good morning",
    "good afternoon",
    "good evening",
    "how are you",
    "what's up",
    "whats up",

    // AI Identity
    "who are you",
    "what are you",
    "are you an ai",
    "are you a bot",
    "are you human",
    "are you real",

    // Learning Sets
    "learning set",
    "learning sets",
    "create a learning set",
    "what is a learning set",
    "flashcard",
    "flashcards",
    "study set",
    "revision set",

    // Feedback / Reactions
    "great app",
    "nice app",
    "love this",
    "this is good",
    "awesome",
    "amazing app",
  ];

  return keywords.some((kw) => question.toLowerCase().includes(kw));
};

export default isZenithDocsQuestion;
