# server/Dockerfile
FROM node:20-alpine

# Set working dir inside container
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production deps for API
RUN npm install --omit=dev

# Copy all source files
COPY . .

# Background worker 
CMD ["npm", "run", "worker"]